name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Angular - AWS S3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync dist/user-management/ s3://user-management-229015217380-us-east-1-an \
            --delete \
            --cache-control "max-age=31536000,public" \
            --exclude "index.html"

          aws s3 cp dist/user-management/index.html s3://user-management-229015217380-us-east-1-an/index.html \
            --cache-control "no-cache,no-store,must-revalidate"